accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns=[
    path('register', views.register, name='register'),
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
]

onlyqual/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from accounts import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('accounts/',include('accounts.urls')),
    path('userprofile/',include('userprofile.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns=[
    path('view_profile', views.view_profile, name='view_profile'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    # path('list_profiles', views.list_profiles, name='list_profiles')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

modprofile/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    Domain_Choices = [
        ('HEALTHCARE', 'Healthcare'),
        ('TECHNOLOGY', 'Technology'),
        ('FINANCE', 'Finance'),
        ('LEGAL', 'Legal'),
        ('EDUCATION', 'Education'),
        ('AGRICULTURE', 'Agriculture')
    ]
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    year_of_exp = models.IntegerField()
    work_domain = models.CharField(max_length=20, choices=Domain_Choices)
    linkedin_url = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    Domain_Choices = [
        ('HEALTHCARE', 'Healthcare'),
        ('TECHNOLOGY', 'Technology'),
        ('FINANCE', 'Finance'),
        ('LEGAL', 'Legal'),
        ('EDUCATION', 'Education'),
        ('AGRICULTURE', 'Agriculture')
    ]
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    year_of_exp = models.IntegerField()
    work_domain = models.CharField(max_length=20, choices=Domain_Choices)
    linkedin_url = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

accounts/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class UserForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ['first_name','last_name','username','password','email']

userprofile/forms.py
from django.forms import ModelForm
from django import forms
from userprofile.models import UserProfileInfo
from django.contrib.auth.models import User

class UserProfileInfoForm(ModelForm):
     class Meta:
         model = UserProfileInfo
         fields = ['year_of_exp','work_domain', 'linkedin_url', 'profile_pic']


class UserChangeForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','username','email']

    def __init__(self, *args, **kwargs):
        super(UserChangeForm, self).__init__(*args, **kwargs)
        f = self.fields.get('user_permissions', None)
        if f is not None:
            f.queryset = f.queryset.select_related('content_type')

accounts/views.py
from django.shortcuts import render, redirect
from accounts.forms import UserForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages


# Create your views here.

# Home Page
def index(request):
    return render(request,'index.html')

# Logout
@login_required
def user_logout(request):
    logout(request)
    return redirect('index')

# Registration 
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        if user_form.is_valid():                                                                    # User validation
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')               # Auto-login after registration        
            return redirect('index')
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()
    return render(request,'registration.html',
                          {'user_form':user_form,
                           'registered':registered})

# Log-in                          
def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)                                   # Calling authentication
        if user:
            if user.is_active:
                login(request,user)
                return redirect('index')
            else:
                messages.warning(request, 'Your account is inactive')
        else:
            messages.error(request, 'You have entered the wrong credential')
            return HttpResponseRedirect('login')
    else:
        return render(request, 'login.html', {})

userprofile/views.py
from django.shortcuts import render, redirect
from userprofile.models import UserProfileInfo
from .forms import UserProfileInfoForm, UserChangeForm
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.


def view_profile(request):
    return render(request, 'view_profile.html')


def edit_profile(request):
    if request.method == 'POST':
        form = UserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('view_profile')
    else:
        form = UserChangeForm(instance=request.user)
        return render(request, 'edit_profile.html', {'form': form})


# def list_profiles(request):
#     lists = UserProfileInfo.objects.filter(user=request.user)
#     return render(request, {'lists': lists})
    

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">OnlyQual</a></li>  
          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'userprofile:view_profile' %}">Profile</a></li>
            <li><a class="navbar-link" href="{% url 'accounts:logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'accounts:register' %}">Register</a></li>     
            <li><a class="navbar-link" href="{% url 'accounts:login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/edit_profile.html
{% extends "base.html" %}
{% load static %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        {% if profile_update %}
        <h2>Thank you! Your profile has been updated.</h2>
        <a href="userprofile/view_profile">Go Back to Profile!</a>
        {% else %}
        <h2>Please fill or update your profile.</h2>
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="Submit">Submit</button>
            <a href="view_profile"><input type="button" name="cancel" value="Cancel" /></a>
        </form>
        {% endif %}
    </div>
</div>
  
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the OnlyQual !</h1>
    {% if user.is_authenticated %}
        <h2>Hello! {{ user.first_name }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Login here :</h1>
    <form method="post" action="{% url 'accounts:login' %}">
      
          {% csrf_token %}
         
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
          <label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
          <input type="submit" name="" value="Login">
    </form>
  </div>
</div>
<div>
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li class="message.tags">{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}
</div>

{% endblock %}

templates/registration.html
{% extends "base.html" %}
{% load static %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
        <form method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/view_profile.html
{% extends "base.html" %}
{% load static %}
{% block body_block %}
    <div class="container">
        <div class="jumbotron">
            {% if user.is_authenticated %}
            <h1>My Account</h1>
            <h3>First Name: {{user.first_name}}</h3>
            <h3>Last Name: {{user.last_name}}</h3>
            <h3>Username: {{user.username}}</h3>
            <h3>Email: {{user.email}}</h3>
            <h3>Years of experience: {{user.userprofileinfo.year_of_exp}}</h3>
            <h3>Work Domain: {{user.userprofileinfo.work_domain}}</h3>
            <h3>Profile URL: {{user.userprofileinfo.linkedin_url}}</h3>
            <h3>Profile Photo: <img src="{{user.userprofileinfo.profile_pic.url}}" alt="Profile Pic" width="100" height="120">
            {% endif %}
        </div>
        <div>
            <form action='edit_profile'>
                <input type='submit' value='Update'>
            </form>
            <Label></Label>
        </div>
    </div>

  
{% endblock %}